id: outlook-default
name: Blank snippet
description: Create a new snippet from a blank template.
author: OfficeDev
host: OUTLOOK
api_set: null
script:
    content: |
        $("#run").click(run);

        function run() {
            const userProfile = Office.context.mailbox.userProfile;
            console.log(`Hello ${userProfile.displayName}`);
        }
    language: typescript
scriptContextSwitch:
    content: |
        $("#run").click(run);

        function run() {
            Office.context.mailbox.addHandlerAsync(Office.EventType.ItemChanged, itemChanged);
            UpdateTaskPaneUI(Office.context.mailbox.item);
            var msgFrom = Office.context.mailbox.item.from;

            console.log("Message received from: " + msgFrom.displayName + " (" + msgFrom.emailAddress + ")");
            const userProfile = Office.context.mailbox.userProfile;
            console.log(`Hello ${userProfile.displayName}`);
        }

        function UpdateTaskPaneUI(item) {
            if (item != null) console.log(item.subject);
        }
        
        function itemChanged(eventArgs) {
            UpdateTaskPaneUI(Office.context.mailbox.item);
        }
        
    language: typescript
template:
    content: |
        <button id="run" class="ms-Button">
            <span class="ms-Button-label">Run</span>
        </button>
    language: html
style:
    content: |-
        section.samples {
            margin-top: 20px;
        }

        section.samples .ms-Button, section.setup .ms-Button {
            display: block;
            margin-bottom: 5px;
            margin-left: 20px;
            min-width: 80px;
        }
    language: css
libraries: |
    https://appsforoffice.microsoft.com/lib/1/hosted/office.js
    @types/office-js

    office-ui-fabric-js@1.4.0/dist/css/fabric.min.css
    office-ui-fabric-js@1.4.0/dist/css/fabric.components.min.css

    core-js@2.4.1/client/core.min.js
    @types/core-js

    jquery@3.1.1
    @types/jquery@3.3.1